import type { FieldSpecies } from "@shared/species";

export const locales = ["en", "fr", "ar"] as const;
export type Locale = (typeof locales)[number];

type MessageMap = Record<string, string>;

const messages: Record<Locale, MessageMap> = {
  en: {
    "nav.scan": "Scan", "nav.archive": "Archive", "nav.map": "Map", "nav.local": "local field archive", "nav.language": "Language",
    "home.eyebrow": "CropGuide · orchard signal log", "home.title": "Listen closer", "home.titleAccent": "to the grove.", "home.lead": "A calm field companion for making small, useful notes about what your orchard is telling you.", "home.madeForField": "made for orchard walks", "home.offlineReady": "offline queue ready", "home.queueOne": "{count} scan is waiting safely on this device and will resend automatically.", "home.queueMany": "{count} scans are waiting safely on this device and will resend automatically.", "home.newNote": "new field note", "home.readLeaf": "Read a leaf", "home.leafPhoto": "Leaf photo", "home.choosePhoto": "Choose a leaf photo", "home.preparing": "Preparing your image…", "home.uploadHint": "Upload from your gallery or files. CropGuide will optimise it for the field.", "home.replacePhoto": "Choose another image", "home.lowDetail": "Small source image: results may be less reliable.", "home.preparedImage": "Prepared image · {dimensions} · {size}", "home.species": "Crop species", "home.gpsCaptured": "Location captured", "home.findingLocation": "Finding location…", "home.gpsUnavailable": "GPS unavailable", "home.gpsAtScan": "GPS at scan time", "home.gpsAuto": "Captured automatically when you submit.", "home.refresh": "Refresh", "home.capture": "Capture", "home.analyse": "Analyse field scan", "home.experimental": "By continuing you acknowledge results are experimental only and are not treatment advice.", "home.guideMark": "from ground to signal", "home.guideTitle": "A clear photo gives the grove a clearer voice.", "home.stepOne": "Choose one affected leaf from your gallery or files.", "home.stepTwo": "Keep sunlight soft; avoid harsh shadows.", "home.stepThree": "Treat the result as a note to inspect, not a verdict.", "home.guideWarning": "Use results to guide observation, never as a stand-alone pesticide or treatment decision.",
    "toast.unsupported": "Choose a JPEG, PNG, or WebP photo.", "toast.tooLarge": "Choose a photo smaller than 16 MB.", "toast.unreadable": "The photo could not be read.", "toast.addPhoto": "Add a leaf photo before analysing.", "toast.offlineSaved": "Saved on this device. CropGuide will analyse it automatically when you reconnect.", "toast.completed": "Analysis complete. Your field note has been saved.", "toast.badPhoto": "CropGuide could not process this photo. Please choose another clear leaf image.", "toast.retry": "Scan saved on this device. It will retry automatically when the service is reachable.",
    "history.eyebrow": "field archive", "history.title": "Every leaf leaves a trace.", "history.lead": "Review saved scans, compare observations, and return to the exact field evidence.", "history.filter": "Filter by crop species", "history.loading": "Loading field notes…", "history.emptyTitle": "No scans yet", "history.emptyLead": "Your completed leaf checks will appear here with their image, time, and top health finding.", "history.start": "Start a field scan", "history.scan": "scan #{id}", "history.gps": "GPS attached", "history.previous": "Previous", "history.next": "Next", "history.page": "Page {page}",
    "result.loading": "Loading analysis…", "result.missing": "This scan could not be found.", "result.archive": "Field archive", "result.observation": "{species} observation", "result.experimental": "experimental only", "result.healthSignal": "health signal", "result.likelyHealthy": "likely healthy", "result.closerLook": "needs a closer look", "result.healthyLead": "The service considered this sample likely healthy.", "result.inspectLead": "Treat this as a prompt for closer field inspection, not a diagnosis.", "result.plantDetected": "plant detected", "result.plantUnavailable": "plant confidence unavailable", "result.gps": "GPS attached", "result.identification": "Plant identification", "result.health": "Health assessment", "result.noIdentification": "No identification candidates were returned.", "result.noHealth": "No health candidates were returned.", "result.disclaimer": "Results are probabilistic image assessments. Inspect symptoms in context and seek qualified local agricultural guidance before making treatment or pesticide decisions.", "result.raw": "View full raw JSON",
    "map.eyebrow": "orchard overview", "map.title": "See the field, not just a leaf.", "map.lead": "Each pin represents a scan that carried GPS coordinates from the device at capture time.", "map.count": "{count} geotagged scans", "map.private": "Pins stay in this browser’s field log", "map.empty": "No GPS-backed scans yet. Allow location on the scan page and your next field check will appear here.", "map.coordinate": "Coordinate overview of field scans", "map.legend": "Coordinate view — pins keep their relative field position", "map.fallback": "Map tiles could not be loaded here, so CropGuide is showing a private coordinate map instead. Each scan remains tied to its exact latitude and longitude.", "map.fieldScan": "field scan",
    "status.healthy": "likely healthy", "status.pending": "assessment pending", "status.none": "no health signal returned",
    "notFound.title": "Page not found", "notFound.lead": "Sorry, the page you are looking for doesn't exist. It may have been moved or deleted.", "notFound.home": "Go home",
    "species.all": "All crops", "species.olive": "Olive", "species.pomegranate": "Pomegranate", "species.fig": "Fig", "species.almond": "Almond", "species.citrus": "Citrus", "species.grapevine": "Grapevine", "species.date_palm": "Date palm", "species.stone_fruit": "Stone fruit", "species.unknown": "Not sure / Other",
  },
  fr: {
    "nav.scan": "Analyse", "nav.archive": "Archives", "nav.map": "Carte", "nav.local": "archives locales", "nav.language": "Langue",
    "home.eyebrow": "CropGuide · journal du verger", "home.title": "Écoutez mieux", "home.titleAccent": "votre verger.", "home.lead": "Un compagnon de terrain calme pour noter ce que votre verger vous indique.", "home.madeForField": "pour les tournées au verger", "home.offlineReady": "file hors ligne prête", "home.queueOne": "{count} analyse attend en sécurité sur cet appareil et sera renvoyée automatiquement.", "home.queueMany": "{count} analyses attendent en sécurité sur cet appareil et seront renvoyées automatiquement.", "home.newNote": "nouvelle note terrain", "home.readLeaf": "Lire une feuille", "home.leafPhoto": "Photo de feuille", "home.choosePhoto": "Choisir une photo de feuille", "home.preparing": "Préparation de votre image…", "home.uploadHint": "Importez depuis la galerie ou les fichiers. CropGuide l’optimisera pour le terrain.", "home.replacePhoto": "Choisir une autre image", "home.lowDetail": "Image source petite : les résultats peuvent être moins fiables.", "home.preparedImage": "Image préparée · {dimensions} · {size}", "home.species": "Culture", "home.gpsCaptured": "Position enregistrée", "home.findingLocation": "Recherche de position…", "home.gpsUnavailable": "GPS indisponible", "home.gpsAtScan": "GPS lors de l’analyse", "home.gpsAuto": "Capturé automatiquement à l’envoi.", "home.refresh": "Actualiser", "home.capture": "Capturer", "home.analyse": "Analyser la feuille", "home.experimental": "En continuant, vous reconnaissez que les résultats sont expérimentaux et ne constituent pas un conseil de traitement.", "home.guideMark": "du terrain au signal", "home.guideTitle": "Une photo claire donne une voix plus nette au verger.", "home.stepOne": "Choisissez une feuille affectée dans votre galerie ou vos fichiers.", "home.stepTwo": "Privilégiez une lumière douce et évitez les ombres fortes.", "home.stepThree": "Considérez le résultat comme une note à vérifier, pas comme un verdict.", "home.guideWarning": "Utilisez les résultats pour guider l’observation, jamais comme décision autonome de pesticide ou de traitement.",
    "toast.unsupported": "Choisissez une image JPEG, PNG ou WebP.", "toast.tooLarge": "Choisissez une photo de moins de 16 Mo.", "toast.unreadable": "La photo n’a pas pu être lue.", "toast.addPhoto": "Ajoutez une photo de feuille avant l’analyse.", "toast.offlineSaved": "Enregistré sur cet appareil. CropGuide l’analysera automatiquement après reconnexion.", "toast.completed": "Analyse terminée. Votre note terrain a été enregistrée.", "toast.badPhoto": "CropGuide n’a pas pu traiter cette photo. Choisissez une feuille nette.", "toast.retry": "Analyse enregistrée sur cet appareil. Elle réessaiera automatiquement lorsque le service sera disponible.",
    "history.eyebrow": "archives terrain", "history.title": "Chaque feuille laisse une trace.", "history.lead": "Consultez les analyses enregistrées, comparez les observations et retrouvez la preuve terrain.", "history.filter": "Filtrer par culture", "history.loading": "Chargement des notes terrain…", "history.emptyTitle": "Aucune analyse", "history.emptyLead": "Vos contrôles terminés apparaîtront ici avec leur image, leur heure et leur principal signal de santé.", "history.start": "Lancer une analyse", "history.scan": "analyse #{id}", "history.gps": "GPS joint", "history.previous": "Précédent", "history.next": "Suivant", "history.page": "Page {page}",
    "result.loading": "Chargement de l’analyse…", "result.missing": "Cette analyse est introuvable.", "result.archive": "Archives terrain", "result.observation": "Observation : {species}", "result.experimental": "expérimental uniquement", "result.healthSignal": "signal de santé", "result.likelyHealthy": "probablement sain", "result.closerLook": "à inspecter de plus près", "result.healthyLead": "Le service considère probablement cet échantillon comme sain.", "result.inspectLead": "Utilisez ceci comme invitation à inspecter le terrain, pas comme diagnostic.", "result.plantDetected": "plante détectée", "result.plantUnavailable": "confiance plante indisponible", "result.gps": "GPS joint", "result.identification": "Identification de la plante", "result.health": "Évaluation de santé", "result.noIdentification": "Aucun candidat d’identification n’a été renvoyé.", "result.noHealth": "Aucun candidat de santé n’a été renvoyé.", "result.disclaimer": "Les résultats sont des évaluations d’images probabilistes. Inspectez les symptômes dans leur contexte et consultez un professionnel agricole local qualifié avant toute décision de traitement ou de pesticide.", "result.raw": "Voir le JSON brut complet",
    "map.eyebrow": "vue du verger", "map.title": "Voir le terrain, pas seulement une feuille.", "map.lead": "Chaque repère représente une analyse avec les coordonnées GPS de l’appareil au moment de la capture.", "map.count": "{count} analyses géolocalisées", "map.private": "Les repères restent dans le journal de ce navigateur", "map.empty": "Aucune analyse avec GPS. Autorisez la position sur la page d’analyse et le prochain contrôle apparaîtra ici.", "map.coordinate": "Vue des coordonnées des analyses", "map.legend": "Vue par coordonnées — les repères gardent leur position relative", "map.fallback": "Les tuiles de carte n’ont pas pu être chargées. CropGuide affiche donc une carte privée par coordonnées. Chaque analyse reste liée à sa latitude et sa longitude.", "map.fieldScan": "analyse terrain",
    "status.healthy": "probablement sain", "status.pending": "évaluation en attente", "status.none": "aucun signal de santé renvoyé",
    "notFound.title": "Page introuvable", "notFound.lead": "Désolé, la page recherchée n’existe pas. Elle a peut-être été déplacée ou supprimée.", "notFound.home": "Retour à l’accueil",
    "species.all": "Toutes les cultures", "species.olive": "Olivier", "species.pomegranate": "Grenadier", "species.fig": "Figuier", "species.almond": "Amandier", "species.citrus": "Agrumes", "species.grapevine": "Vigne", "species.date_palm": "Palmier dattier", "species.stone_fruit": "Fruits à noyau", "species.unknown": "Je ne sais pas / Autre",
  },
  ar: {
    "nav.scan": "فحص", "nav.archive": "السجل", "nav.map": "الخريطة", "nav.local": "سجل ميداني محلي", "nav.language": "اللغة",
    "home.eyebrow": "CropGuide · سجل إشارات البستان", "home.title": "أنصت أكثر", "home.titleAccent": "إلى بستانك.", "home.lead": "مرافق ميداني هادئ يساعدك على تدوين ملاحظات صغيرة ومفيدة عن حالة بستانك.", "home.madeForField": "مصمم لجولات البستان", "home.offlineReady": "طابور دون اتصال جاهز", "home.queueOne": "هناك فحص واحد محفوظ بأمان على هذا الجهاز وسيُرسل تلقائياً.", "home.queueMany": "هناك {count} فحوصات محفوظة بأمان على هذا الجهاز وستُرسل تلقائياً.", "home.newNote": "ملاحظة ميدانية جديدة", "home.readLeaf": "تحليل ورقة", "home.leafPhoto": "صورة الورقة", "home.choosePhoto": "اختر صورة ورقة", "home.preparing": "يجري تجهيز الصورة…", "home.uploadHint": "ارفعها من المعرض أو الملفات. سيُحسن CropGuide تجهيزها للميدان.", "home.replacePhoto": "اختر صورة أخرى", "home.lowDetail": "الصورة الأصلية صغيرة؛ وقد تكون النتائج أقل موثوقية.", "home.preparedImage": "تم تجهيز الصورة · {dimensions} · {size}", "home.species": "المحصول", "home.gpsCaptured": "تم حفظ الموقع", "home.findingLocation": "جارٍ تحديد الموقع…", "home.gpsUnavailable": "GPS غير متاح", "home.gpsAtScan": "GPS عند الفحص", "home.gpsAuto": "يُلتقط تلقائياً عند الإرسال.", "home.refresh": "تحديث", "home.capture": "التقاط", "home.analyse": "حلّل الفحص الميداني", "home.experimental": "بالمتابعة، تقر بأن النتائج تجريبية فقط وليست نصيحة علاجية.", "home.guideMark": "من الأرض إلى الإشارة", "home.guideTitle": "الصورة الواضحة تمنح البستان صوتاً أوضح.", "home.stepOne": "اختر ورقة واحدة متأثرة من المعرض أو الملفات.", "home.stepTwo": "استخدم ضوءاً ناعماً وتجنب الظلال القوية.", "home.stepThree": "تعامل مع النتيجة كملاحظة للفحص وليست حكماً نهائياً.", "home.guideWarning": "استخدم النتائج لتوجيه الملاحظة فقط، وليس لاتخاذ قرار مستقل بشأن المبيدات أو العلاج.",
    "toast.unsupported": "اختر صورة JPEG أو PNG أو WebP.", "toast.tooLarge": "اختر صورة أصغر من 16 ميغابايت.", "toast.unreadable": "تعذرت قراءة الصورة.", "toast.addPhoto": "أضف صورة ورقة قبل التحليل.", "toast.offlineSaved": "حُفظت على هذا الجهاز. سيحللها CropGuide تلقائياً عند عودة الاتصال.", "toast.completed": "اكتمل التحليل وحُفظت ملاحظتك الميدانية.", "toast.badPhoto": "تعذر على CropGuide معالجة هذه الصورة. اختر صورة أوضح للورقة.", "toast.retry": "حُفظ الفحص على هذا الجهاز وسيعاد تلقائياً عند توفر الخدمة.",
    "history.eyebrow": "الأرشيف الميداني", "history.title": "كل ورقة تترك أثراً.", "history.lead": "راجع الفحوصات المحفوظة وقارن الملاحظات وارجع إلى الدليل الميداني نفسه.", "history.filter": "التصفية حسب المحصول", "history.loading": "جارٍ تحميل الملاحظات الميدانية…", "history.emptyTitle": "لا توجد فحوصات بعد", "history.emptyLead": "ستظهر فحوصات الأوراق المكتملة هنا مع الصورة والوقت وأبرز إشارة صحية.", "history.start": "ابدأ فحصاً ميدانياً", "history.scan": "فحص #{id}", "history.gps": "تم إرفاق GPS", "history.previous": "السابق", "history.next": "التالي", "history.page": "الصفحة {page}",
    "result.loading": "جارٍ تحميل التحليل…", "result.missing": "تعذر العثور على هذا الفحص.", "result.archive": "الأرشيف الميداني", "result.observation": "ملاحظة {species}", "result.experimental": "تجريبي فقط", "result.healthSignal": "إشارة صحية", "result.likelyHealthy": "يبدو سليماً", "result.closerLook": "يحتاج فحصاً أقرب", "result.healthyLead": "اعتبر النظام هذه العينة سليمة على الأرجح.", "result.inspectLead": "اعتبر هذه النتيجة دعوة لفحص ميداني أدق، وليست تشخيصاً.", "result.plantDetected": "تم اكتشاف نبات", "result.plantUnavailable": "ثقة اكتشاف النبات غير متاحة", "result.gps": "تم إرفاق GPS", "result.identification": "تحديد النبات", "result.health": "تقييم الصحة", "result.noIdentification": "لم تُعد أي مرشحات لتحديد النبات.", "result.noHealth": "لم تُعد أي مرشحات للحالة الصحية.", "result.disclaimer": "النتائج تقييمات احتمالية للصور. افحص الأعراض ضمن سياقها واستشر مختصاً زراعياً محلياً مؤهلاً قبل اتخاذ قرار علاج أو مبيد.", "result.raw": "عرض ملف JSON الخام الكامل",
    "map.eyebrow": "نظرة على البستان", "map.title": "شاهد الحقل، لا الورقة فقط.", "map.lead": "يمثل كل مؤشر فحصاً حفظ إحداثيات GPS من الجهاز عند الالتقاط.", "map.count": "{count} فحوصات محددة جغرافياً", "map.private": "تبقى المؤشرات في السجل الميداني لهذا المتصفح", "map.empty": "لا توجد فحوصات مرتبطة بـ GPS بعد. اسمح بالموقع من صفحة الفحص وسيظهر الفحص التالي هنا.", "map.coordinate": "نظرة إحداثية للفحوصات الميدانية", "map.legend": "عرض بالإحداثيات — تحتفظ المؤشرات بمواقعها النسبية في الحقل", "map.fallback": "تعذر تحميل طبقات الخريطة هنا، لذلك يعرض CropGuide خريطة إحداثيات خاصة. يبقى كل فحص مرتبطاً بخط العرض والطول الدقيقين.", "map.fieldScan": "فحص ميداني",
    "status.healthy": "يبدو سليماً", "status.pending": "التقييم قيد الانتظار", "status.none": "لم تُعد إشارة صحية",
    "notFound.title": "الصفحة غير موجودة", "notFound.lead": "عذراً، الصفحة التي تبحث عنها غير موجودة. قد تكون نُقلت أو حُذفت.", "notFound.home": "العودة للرئيسية",
    "species.all": "كل المحاصيل", "species.olive": "زيتون", "species.pomegranate": "رمان", "species.fig": "تين", "species.almond": "لوز", "species.citrus": "حمضيات", "species.grapevine": "كروم العنب", "species.date_palm": "نخيل التمر", "species.stone_fruit": "فواكه نَوَوية", "species.unknown": "غير متأكد / أخرى",
  },
};

const messageOverrides: Partial<Record<Locale, Partial<MessageMap>>> = {
  en: {
    "home.preparedImage": "Prepared locally · {dimensions} · {size}",
    "home.uploadHint": "Upload an ordinary photo from your gallery or files. CropGuide prepares it automatically for analysis.",
    "home.guideTitle": "CropGuide prepares ordinary field photos automatically.",
    "home.stepOne": "Upload the field photo as it was captured.",
    "home.stepTwo": "CropGuide normalizes tone and adds a detail view automatically.",
    "toast.badPhoto": "CropGuide could not process this field photo. Try a different JPEG, PNG, or WebP file.",
    "result.closerLook": "disease assessment was inconclusive",
    "result.inspectLead": "The plant was identified, but the disease assessment was inconclusive. Treat this as a prompt for closer field inspection, not a diagnosis.",
    "result.noHealth": "The plant was identified, but no reliable disease candidate was returned from this image.",
  },
  fr: {
    "home.preparedImage": "Préparée sur l’appareil · {dimensions} · {size}",
    "home.uploadHint": "Importez une photo ordinaire depuis la galerie ou les fichiers. CropGuide la prépare automatiquement pour l’analyse.",
    "home.guideTitle": "CropGuide prépare automatiquement les photos de terrain ordinaires.",
    "home.stepOne": "Importez la photo telle qu’elle a été prise sur le terrain.",
    "home.stepTwo": "CropGuide normalise le rendu et ajoute automatiquement une vue de détail.",
    "toast.badPhoto": "CropGuide n’a pas pu traiter cette photo terrain. Essayez un autre fichier JPEG, PNG ou WebP.",
    "result.closerLook": "évaluation de maladie non concluante",
    "result.inspectLead": "La plante a été identifiée, mais l’évaluation de maladie est restée non concluante. Utilisez ceci comme invitation à inspecter le terrain, pas comme diagnostic.",
    "result.noHealth": "La plante a été identifiée, mais aucun candidat de maladie fiable n’a été renvoyé pour cette image.",
  },
  ar: {
    "home.preparedImage": "جُهزت على الجهاز · {dimensions} · {size}",
    "home.uploadHint": "ارفع صورة عادية من المعرض أو الملفات. يجهّزها CropGuide تلقائياً للتحليل.",
    "home.guideTitle": "يجهّز CropGuide الصور الميدانية العادية تلقائياً.",
    "home.stepOne": "ارفع الصورة كما التُقطت في الحقل.",
    "home.stepTwo": "يُوازن CropGuide الألوان ويضيف لقطة تفاصيل تلقائياً.",
    "toast.badPhoto": "تعذر على CropGuide معالجة هذه الصورة الميدانية. جرّب ملفاً آخر JPEG أو PNG أو WebP.",
    "result.closerLook": "تقييم المرض غير حاسم",
    "result.inspectLead": "تم تحديد النبات، لكن تقييم المرض لم يكن حاسماً. اعتبر هذه النتيجة دعوة لفحص ميداني أدق، وليست تشخيصاً.",
    "result.noHealth": "تم تحديد النبات، لكن لم يُعد مرشح مرضي موثوق من هذه الصورة.",
  },
};

export function translate(locale: Locale, key: string, values: Record<string, string | number> = {}) {
  return (messageOverrides[locale]?.[key] ?? messages[locale][key] ?? messageOverrides.en?.[key] ?? messages.en[key] ?? key).replace(/\{(\w+)\}/g, (_, name: string) => String(values[name] ?? `{${name}}`));
}

export function speciesMessageKey(species: FieldSpecies) {
  return `species.${species}`;
}

export function dateLocale(locale: Locale) {
  return locale === "ar" ? "ar-TN" : locale === "fr" ? "fr-FR" : "en-GB";
}
